### ISSUE TITLE
FindingErrors - не особо понял линк

### ISSUE THREAD

**Issue by aademid** [NIBugakov/ProtocolOfDisagreementUiPath#6]
![image](https://github.com/NIBugakov/ProtocolOfDisagreementUiPath/assets/130755894/d72e03ea-7f81-4063-b583-80f7935d00a1)

Пока не особо понял, но основное - Try\Catch? можно же было условие сделать...

**Comment by aademid** [comment]
> ![image](https://private-user-images.githubusercontent.com/130755894/311725441-d72e03ea-7f81-4063-b583-80f7935d00a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjUwNjgsIm5iZiI6MTcxMDE2NDc2OCwicGF0aCI6Ii8xMzA3NTU4OTQvMzExNzI1NDQxLWQ3MmUwM2VhLTdmODEtNDA2My1iNTgzLTgwZjc5MzVkMDBhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMzQ2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGQyMzZkM2NlMzVkNDY0MzM0MmViOWE4NGMwMDFlYjliOWNjZTJmYzhlNGJiNjJkYzZmODViOTM5ZjA2NGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G6tJ_WGA4QyPgAGEhIPdtPpHy5k1OfDNimQamyyeGsA)
> 
> Пока не особо понял, но основное - Try\Catch? можно же было условие сделать...

Вроде понял линк, но описание так себе будем честны

**Comment by aademid** [comment]
Ну и там по скрипту везде так, в пиксе такое разве было?

**Comment by NIBugakov** [comment]
Ну эти блин названия с пикса перекочевали

**Comment by NIBugakov** [comment]
Да была +- такая же логика , по названиям ,как-то забыл ,визуально кажется что они уже названы ,когда быстро просматриваю ,но это название просто сохранилось от линка ,который на правильность ключей проверяет
